Update usernickname in prvmsg
cybattis/ft_transcendence pull request #55
Opened 2023-08-23 16:09 UTC by Draxuxe

2023-08-24 06:58 UTC, Nowa-k requested changes
So many probleme

2023-08-24 19:33 UTC, cybattis commented on src/api/src/chat/chat.gateway.ts
> +    //await this.channelService.joinOldChannel(socket, username);
C'est normal ça ?

2023-08-27 20:09 UTC, Draxuxe commented on src/api/src/chat/chat.gateway.ts
> +    //await this.channelService.joinOldChannel(socket, username);
Alors avec Alexis on a regardé et on avait testé parce que il l utilisait pour la liste dans le front et j ai fait une autre manière qui marche mieux donc en soit on peut laisse mais normalement cette fonction est plus utilisee

2023-08-27 20:11 UTC, cybattis commented on src/api/src/chat/chat.gateway.ts
> +    //await this.channelService.joinOldChannel(socket, username);
ok, ben sis c'est plus utilisé on peux supprimer la ligne.

2023-08-27 20:11 UTC, cybattis approved these changes
okok

2023-08-27 20:13 UTC, cybattis approved these changes
okok

2023-08-27 20:13 UTC, merged